export {
  DASHBOARD_PREFIX,
  DASHBOARD_API_REQUESTS,
  DASHBOARD_API_EVENTS,
  DASHBOARD_API_FLOWS,
  DASHBOARD_API_CLEAR,
  DASHBOARD_API_LOGS,
  DASHBOARD_API_FETCHES,
  DASHBOARD_API_ERRORS,
  DASHBOARD_API_QUERIES,
  DASHBOARD_API_INGEST,
  DASHBOARD_API_METRICS,
  DASHBOARD_API_ACTIVITY,
  DASHBOARD_API_METRICS_LIVE,
  DASHBOARD_API_INSIGHTS,
  DASHBOARD_API_SECURITY,
  DASHBOARD_API_TAB,
  DASHBOARD_API_FINDINGS,
  DASHBOARD_API_FINDINGS_REPORT,
  VALID_TABS,
} from "./routes.js";

export {
  MAX_REQUEST_ENTRIES,
  DEFAULT_MAX_BODY_CAPTURE,
  DEFAULT_API_LIMIT,
  MAX_TELEMETRY_ENTRIES,
  MAX_TAB_NAME_LENGTH,
  MAX_INGEST_BYTES,
  TERMINAL_TRUNCATE_LENGTH,
  SENSITIVE_MASK_MIN_LENGTH,
  SENSITIVE_MASK_VISIBLE_CHARS,
  MAX_JSON_BODY_BYTES,
  ANALYSIS_DEBOUNCE_MS,
  ISSUE_ID_HASH_LENGTH,
  ISSUES_DATA_VERSION,
  SENSITIVE_MASK_PLACEHOLDER,
  PROJECT_HASH_LENGTH,
  SECRET_SCAN_ARRAY_LIMIT,
  PII_SCAN_ARRAY_LIMIT,
  MIN_SECRET_VALUE_LENGTH,
  FULL_RECORD_MIN_FIELDS,
  LIST_PII_MIN_ITEMS,
  MAX_API_LIMIT,
} from "./limits.js";

export {
  FLOW_GAP_MS,
  SLOW_REQUEST_THRESHOLD_MS,
  MIN_POLLING_SEQUENCE,
  ENDPOINT_TRUNCATE_LENGTH,
  SHUTDOWN_TIMEOUT_MS,
  N1_QUERY_THRESHOLD,
  ERROR_RATE_THRESHOLD_PCT,
  SLOW_ENDPOINT_THRESHOLD_MS,
  MIN_REQUESTS_FOR_INSIGHT,
  HIGH_QUERY_COUNT_PER_REQ,
  CROSS_ENDPOINT_MIN_ENDPOINTS,
  CROSS_ENDPOINT_PCT,
  CROSS_ENDPOINT_MIN_OCCURRENCES,
  REDUNDANT_QUERY_MIN_COUNT,
  LARGE_RESPONSE_BYTES,
  HIGH_ROW_COUNT,
  OVERFETCH_MIN_REQUESTS,
  OVERFETCH_MIN_FIELDS,
  OVERFETCH_MIN_INTERNAL_IDS,
  OVERFETCH_NULL_RATIO,
  REGRESSION_PCT_THRESHOLD,
  REGRESSION_MIN_INCREASE_MS,
  REGRESSION_MIN_REQUESTS,
  QUERY_COUNT_REGRESSION_RATIO,
  OVERFETCH_MANY_FIELDS,
  OVERFETCH_UNWRAP_MIN_SIZE,
  MAX_DUPLICATE_INSIGHTS,
  INSIGHT_WINDOW_PER_ENDPOINT,
  CLEAN_HITS_FOR_RESOLUTION,
  STALE_ISSUE_TTL_MS,
} from "./thresholds.js";

export {
  TRANSPORT_FLUSH_INTERVAL_MS,
  TRANSPORT_FLUSH_BATCH_SIZE,
  SSE_HEARTBEAT_INTERVAL_MS,
  NOISE_HOSTS,
  NOISE_PATH_PATTERNS,
} from "./transport.js";

export {
  METRICS_DIR,
  METRICS_FILE,
  PORT_FILE,
  ISSUES_FILE,
  METRICS_FLUSH_INTERVAL_MS,
  METRICS_MAX_SESSIONS,
  METRICS_MAX_DATA_POINTS,
  ISSUES_FLUSH_INTERVAL_MS,
} from "./metrics.js";

export {
  BRAKIT_REQUEST_ID_HEADER,
  SENSITIVE_HEADER_NAMES,
} from "./headers.js";

export {
  CLOUD_SIGNALS,
  MAX_HEALTH_ERRORS,
  RECOVERY_WINDOW_MS,
  PORT_MIN,
  PORT_MAX,
  LOCALHOST_IPS,
  LOCALHOST_HOSTNAMES,
  URL_PARSE_BASE,
  DIR_MODE_OWNER_ONLY,
  FILE_MODE_OWNER_ONLY,
} from "./network.js";

export {
  MCP_SERVER_NAME,
  MCP_SERVER_VERSION,
  INITIAL_DISCOVERY_TIMEOUT_MS,
  LAZY_DISCOVERY_TIMEOUT_MS,
  CLIENT_FETCH_TIMEOUT_MS,
  HEALTH_CHECK_TIMEOUT_MS,
  DISCOVERY_POLL_INTERVAL_MS,
  MAX_DISCOVERY_DEPTH,
  MAX_TIMELINE_EVENTS,
  MAX_RESOLVED_DISPLAY,
  ENRICHMENT_SEVERITY_FILTER,
} from "./mcp.js";

export {
  CONTENT_ENCODING_GZIP,
  CONTENT_ENCODING_BR,
  CONTENT_ENCODING_DEFLATE,
} from "./encoding.js";

export {
  SEVERITY_ICON,
  SEVERITY_SORT_ORDER,
} from "./severity.js";

export {
  POSTHOG_HOST,
  POSTHOG_CAPTURE_PATH,
  POSTHOG_REQUEST_TIMEOUT_MS,
  POSTHOG_SPAWN_TIMEOUT_MS,
  SIGNAL_EXIT_SIGINT,
  SIGNAL_EXIT_SIGTERM,
  SPEED_BUCKET_THRESHOLDS,
} from "./telemetry.js";

export {
  VALID_ISSUE_STATES,
  VALID_ISSUE_CATEGORIES,
  VALID_AI_FIX_STATUSES,
  VALID_SECURITY_SEVERITIES,
} from "./lifecycle.js";

export {
  SUPPORTED_SOURCE_EXTENSIONS,
  BUILD_CACHE_DIRS,
  FALLBACK_SCAN_DIRS,
} from "./cli.js";
