export const CLOUD_SIGNALS = [
  "VERCEL", "VERCEL_ENV", "NETLIFY", "AWS_LAMBDA_FUNCTION_NAME",
  "AWS_EXECUTION_ENV", "ECS_CONTAINER_METADATA_URI", "GOOGLE_CLOUD_PROJECT",
  "GCP_PROJECT", "K_SERVICE", "AZURE_FUNCTIONS_ENVIRONMENT",
  "WEBSITE_SITE_NAME", "FLY_APP_NAME", "RAILWAY_ENVIRONMENT", "RENDER",
  "HEROKU_APP_NAME", "DYNO", "CF_INSTANCE_GUID", "CF_PAGES",
  "KUBERNETES_SERVICE_HOST",
] as const;

export const MAX_HEALTH_ERRORS = 10;

const LOCALHOST_IPS_TUPLE = ["127.0.0.1", "::1", "::ffff:127.0.0.1"] as const;
const LOCALHOST_HOSTNAMES_TUPLE = ["localhost", "127.0.0.1", "::1"] as const;

export const LOCALHOST_IPS: Set<string> = new Set(LOCALHOST_IPS_TUPLE);
export const LOCALHOST_HOSTNAMES: Set<string> = new Set(LOCALHOST_HOSTNAMES_TUPLE);
